Repository digital-solution-consulting/gsurvey, pull requests merged in 2020-05, with the labels that each got.

#229 Fix bug for outlook email does not support background gradient CSS
  backend/components/v2/email-templates/form.js
  backend/components/v2/users/password.js
Labels: bug

#231 change password , bug reset password , bug side menu for org admin role
  client/src/layouts/components/sidebar/sidemenu/sidemenu.js
  client/src/views/pages/resetPassword.js
  client/src/views/pages/userProfile.js
Labels: bug, enhancement

#232 remove warning and error on each page
  client/src/index.js
  client/src/layouts/components/footer/footer.js
  client/src/layouts/components/navbar/navbar.js
  client/src/layouts/components/sidebar/sidebar.js
  client/src/layouts/components/sidebar/sidemenu/sidemenu.js
  client/src/services/UserAuth.js
  client/src/services/validateRegister.js
  client/src/views/pages/dashboard-all.js
  client/src/views/pages/dashboard-by-department.js
  client/src/views/pages/main.js
  client/src/views/pages/useForm.js
Labels: invalid
