Repository digital-solution-consulting/gsurvey, pull requests merged in 2020-02, with the labels that each got.

#149 add new APIs for admin
  backend/app.js
  backend/components/gsurveys/admin/index.js
  backend/components/v2/admin/index.js
  backend/components/v2/users/index.js
Labels: enhancement

#152 fix return data as object instead of array
  backend/components/v2/admin/index.js
Labels: bug

#153 Initialize api
  backend/components/v2/admin/index.js
  backend/package.json
Labels: enhancement

#154 change method of rename as POST method
  backend/components/v2/admin/index.js
Labels: bug

#155 update gsurvey
  client/package.json
  client/src/app/router.js
  client/src/assets/img/ico/icons8-edit-24.png
  client/src/services/AppConfig.js
  client/src/views/pages/display.js
  client/src/views/pages/main.js
  client/src/views/pages/survey-create.js
Labels: enhancement

#156 update package.json
  client/package.json
Labels: bug

#160 Add new apis for non-login users
  backend/components/helpers/mongodb.js
  backend/components/v2/admin/index.js
  backend/components/v2/users/index.js
  images/architecture.png
  images/ocean.png
  images/tsunami.png
Labels: enhancement

#161 hotfix-invalid-type
  backend/components/v2/admin/index.js
Labels: bug

#162 add login API
  backend/app.js
  backend/components/v2/admin/index.js
  backend/components/v2/admin/user.js
  backend/components/v2/auth/auth.js
  backend/components/v2/auth/index.js
  backend/package.json
Labels: enhancement

#163 Client rewrite for new api
  client/package.json
  client/src/assets/img/DGALogo.png
  client/src/assets/scss/views/pages/survey/admin.css
  client/src/assets/scss/views/pages/survey/survey.css
  client/src/layouts/components/footer/footer.js
  client/src/layouts/components/navbar/navbar.js
  client/src/layouts/components/sidebar/sidemenu/sidemenu.js
  client/src/templateConfig.js
  client/src/views/pages/display.js
  client/src/views/pages/login.js
  client/src/views/pages/main.js
  client/src/views/pages/survey-create.js
Labels: enhancement, good first issue

#157 edit css for surveyjs display
  client/src/assets/scss/views/pages/survey/admin.css
  client/src/assets/scss/views/pages/survey/survey.css
  client/src/layouts/components/sidebar/sidemenu/sidemenu.js
  client/src/views/pages/login.js
  client/src/views/pages/main.js
  client/src/views/pages/survey-create.js
Labels: good first issue

#164 Export data from mongodb to csv file
  backend/config/production.conf-template.js
  scripts/mongo-export-csv.sh
Labels: enhancement

#165 update survey not update version
  client/src/layouts/components/footer/footer.js
  client/src/views/pages/display.js
  client/src/views/pages/main.js
  client/src/views/pages/survey-create.js
Labels: enhancement
