Repository digital-solution-consulting/gsurvey, pull requests merged in 2020-03, with the labels that each got.

#166 result survey
  client/src/app/router.js
  client/src/assets/img/sidebar-bg/survey-bg.jpg
  client/src/views/pages/main.js
  client/src/views/pages/result.js
  client/src/views/pages/survey-create.js
Labels: enhancement

#167 return userid on login
  backend/components/v2/auth/auth.js
Labels: bug

#168 bug display , display result
  client/src/views/pages/display.js
  client/src/views/pages/main.js
  client/src/views/pages/result.js
Labels: bug, enhancement

#170 enable google analytic tracking
  client/src/index.js
Labels: enhancement

#169 bug missing file
  client/src/views/pages/main.js
Labels: bug

#171 change api login , use react-idle-timer module
  client/package.json
  client/src/layouts/components/navbar/navbar.js
  client/src/layouts/components/sidebar/sidemenu/sidemenu.js
  client/src/services/UserAuth.js
  client/src/views/pages/login.js
Labels: bug, enhancement

#172 make access-control-allow configurable
  backend/app.js
  backend/components/v2/admin/index.js
  backend/components/v2/auth/index.js
  backend/components/v2/users/index.js
  backend/config/production.conf-template.js
Labels: enhancement

#173 authen with cookie
  client/src/services/UserAuth.js
  client/src/views/pages/login.js
  client/src/views/pages/main.js
Labels: bug, enhancement, good first issue

#174 add allow origin
  backend/components/v2/admin/index.js
  backend/components/v2/auth/index.js
  backend/components/v2/users/index.js
Labels: enhancement

#175 Set access control allow
  backend/app.js
  backend/components/v2/admin/index.js
  backend/components/v2/auth/index.js
  backend/components/v2/users/index.js
Labels: bug

#176 fix bug when use authentication from backend
  client/src/layouts/components/navbar/navbar.js
  client/src/services/UserAuth.js
  client/src/views/pages/display.js
  client/src/views/pages/login.js
  client/src/views/pages/main.js
  client/src/views/pages/result.js
  client/src/views/pages/survey-create.js
Labels: bug

#177 bug create survey page, bug display result, custom font display survey
  client/src/assets/scss/views/pages/survey/survey.css
  client/src/views/pages/result.js
  client/src/views/pages/survey-create.js
Labels: bug

#182 fix bug user, revise main page display
  client/src/layouts/components/navbar/navbar.js
  client/src/views/pages/main.js
Labels: bug, good first issue

#183 adjust footer , icon disappear , add first row
  client/src/layouts/components/footer/footer.js
  client/src/layouts/components/sidebar/sidebar.js
  client/src/layouts/components/sidebar/sidebarHeader/sidebarHeader.js
  client/src/views/pages/main.js
  client/src/views/pages/survey-create.js
Labels: bug, good first issue

#184 Hot-fix ignore package-lock.json and other configuration
  backend/.gitignore
  backend/package-lock.json
  client/.gitignore
  client/package-lock.json
  client/src/services/AppConfig.js
Labels: bug

#186 translate eng to thai wording
  client/src/layouts/components/navbar/navbar.js
  client/src/views/pages/login.js
  client/src/views/pages/main.js
  client/src/views/pages/result.js
  client/src/views/pages/survey-create.js
Labels: enhancement

#187 revise thai wording
  client/src/views/pages/login.js
  client/src/views/pages/main.js
Labels: enhancement

#188 add timestamp and search with desc order
  backend/components/helpers/mongodb.js
  backend/components/v2/admin/index.js
  backend/components/v2/auth/auth.js
  backend/components/v2/users/index.js
Labels: enhancement

#189 add start scripts by using pm2
  backend/start.sh
  client/start.sh
Labels: enhancement

#190 Client reviseresultpage
  client/public/index.html
  client/src/views/pages/result.js
Labels: good first issue

#191 revise wording to THAI and change logo
  client/public/favicon-gsurvey.png
  client/public/index.html
  client/src/assets/img/logo_gsurvey.png
  client/src/assets/img/logo_gsurvey_login.png
  client/src/layouts/components/navbar/navbar.js
  client/src/layouts/components/sidebar/sidebarHeader/sidebarHeader.js
  client/src/views/pages/display.js
  client/src/views/pages/error.js
  client/src/views/pages/login.js
  client/src/views/pages/main.js
  client/src/views/pages/result.js
Labels: good first issue

#192 add modify date, open survey to new tab , try to change icon color
  client/src/views/pages/main.js
Labels: good first issue

#194 bug login , change error text language at display page
  client/src/services/UserAuth.js
  client/src/views/pages/display.js
  client/src/views/pages/login.js
Labels: bug
