Repository digital-solution-consulting/gsurvey, pull requests merged in 2020-04, with the labels that each got.

#195 add all register , organization api and revise a configuration
  backend/.env-template
  backend/components/helpers/mail.js
  backend/components/helpers/mysql.js
  backend/components/v2/admin/user.js
  backend/components/v2/auth/auth.js
  backend/components/v2/users/index.js
  backend/components/v2/users/organization.js
  backend/components/v2/users/register.js
  backend/config/production.conf-template.js
  backend/package.json
Labels: enhancement

#196 add configuration library
  backend/.gitignore
  backend/config/production.conf.js
Labels: bug

#197 function register page , user management page, forget password page ,…
  client/src/app/router.js
  client/src/services/validateRegister.js
  client/src/views/pages/UserManagement.js
  client/src/views/pages/forgetpassword.js
  client/src/views/pages/login.js
  client/src/views/pages/register.js
  client/src/views/pages/useForm.js
Labels: enhancement

#198 change color page, set value to initial state after submit
  client/src/views/pages/register.js
  client/src/views/pages/useForm.js
Labels: bug, enhancement

#199 add change and reset password
  backend/components/helpers/mail.js
  backend/components/helpers/redis.js
  backend/components/v2/admin/index.js
  backend/components/v2/admin/user.js
  backend/components/v2/auth/auth.js
  backend/components/v2/users/index.js
  backend/components/v2/users/organization.js
  backend/components/v2/users/password.js
  backend/components/v2/users/register.js
  backend/config/production.conf.js
Labels: enhancement

#200 reset password flow
  client/package.json
  client/src/app/router.js
  client/src/views/pages/forgetpassword.js
  client/src/views/pages/register.js
  client/src/views/pages/resetPassword.js
Labels: enhancement

#202 change parameter api , change input type from text to password
  client/src/views/pages/forgetpassword.js
  client/src/views/pages/resetPassword.js
Labels: bug

#203 support origin header instead of using url
  backend/components/v2/users/password.js
Labels: enhancement

#204 bug redirect and bug condition if from response
  client/src/views/pages/resetPassword.js
Labels: bug

#205 V2 backend members
  backend/components/v2/admin/index.js
  backend/components/v2/admin/members.js
  backend/components/v2/users/register.js
Labels: enhancement

#206 add suspension, deletion and approval api
  backend/components/v2/admin/members.js
  backend/components/v2/auth/auth.js
Labels: enhancement

#208 fix format on register email
  backend/components/v2/users/register.js
Labels: enhancement

#209 v2-backend-revise-error-code
  backend/components/v2/auth/auth.js
Labels: enhancement

#210 use insertOne instead of findAndReplaceOne
  backend/components/helpers/mongodb.js
  backend/components/v2/users/index.js
Labels: enhancement

#211 change suspension flag to status
  backend/components/v2/admin/members.js
Labels: enhancement

#212 hotfix-invalid-logic
  backend/components/v2/admin/members.js
Labels: bug

#213 user management, navbar user management
  client/src/layouts/components/sidebar/sidemenu/sidemenu.js
  client/src/views/pages/UserManagement.js
Labels: bug, enhancement

#214 change icon when status is disable,enable
  client/src/views/pages/UserManagement.js
Labels: good first issue

#215 rewrite login page , use err code for display
  client/src/services/UserAuth.js
  client/src/views/pages/login.js
Labels: enhancement, good first issue

#216 password condition, tooltips box
  client/src/services/validateRegister.js
  client/src/views/pages/register.js
  client/src/views/pages/resetPassword.js
Labels: good first issue

#217 cannot build
  client/src/views/pages/login.js
Labels: bug

#218 support paging on getting result api and revise code
  backend/commons/http.js
  backend/components/helpers/mongodb.js
  backend/components/v2/admin/index.js
  backend/components/v2/admin/survey.js
  backend/components/v2/users/index.js
  backend/components/v2/users/survey.js
Labels: enhancement

#219 V2 backend enhance connection pool
  backend/.env-template
  backend/components/helpers/mongodb.js
  backend/config/production.conf.js
Labels: enhancement

#221 V2 backend enhance connection pool
  backend/.env-template
  backend/commons/logger.js
  backend/components/helpers/mongodb.js
  backend/config/production.conf.js
Labels: bug, enhancement

#222 add prefix, profile APIs
  backend/components/v2/admin/index.js
  backend/components/v2/admin/user.js
  backend/components/v2/users/index.js
  backend/components/v2/users/organization.js
Labels: enhancement

#223 add user profile ,deleted console.log
  client/src/app/router.js
  client/src/layouts/components/navbar/navbar.js
  client/src/views/pages/UserManagement.js
  client/src/views/pages/main.js
  client/src/views/pages/userProfile.js
Labels: enhancement, good first issue

#225 Client profile fixed2
  client/src/app/router.js
  client/src/views/pages/proFile.js
Labels: bug

#226 declare global variable, clear router , deleted unused file
  client/src/app/router.js
  client/src/index.js
  client/src/services/AuthService.js
  client/src/services/PostData.js
  client/src/services/UserAuth.js
  client/src/views/pages/login.js
  client/src/views/pages/survey-create.js
Labels: good first issue

#230 bug register, update profile user
  client/src/services/validateRegister.js
  client/src/views/pages/register.js
  client/src/views/pages/userProfile.js
Labels: bug, enhancement
